### ISSUE TITLE
What is the unit of the "packet_loss" in ping.csv?

### ISSUE THREAD

**Issue by Rango-T10000** [sys-uos/Starlink-on-the-Road#1]
Nice work. I have a question about the second file: ping.csv.
When I open the file, I found the "packet_loss" item:
<img width="1317" alt="image" src="https://github.com/user-attachments/assets/b973d692-9f25-4ccb-b090-ed660c9e46dd">
I want to know that what is the unit of the "packet_loss"?
If this indicates the packet loss ratio, I think all the value should less than 1 (100%).
But I found that there are some value like 20.2? Does it mean 20.2%?

**Comment by elanfer** [comment]
Hi, you're right this is percent, e.g., 20.2 means 20.2% (0.202).

Cheers, Eric

**Comment by Rango-T10000** [comment]
> Hi, you're right this is percent, e.g., 20.2 means 20.2% (0.202).
> 
> Cheers, Eric
Really thanks for your reply including here and email. 
I have another question that which col means RRT(Round Trip Time)?
The "ping_avg" ? And is the unit ms?

**Comment by elanfer** [comment]
Hi Rango,
ping_avg is the round trip time average over time. We send several icmp packets. We do also provide worst, best etc. 
These values are measured in ms.
